apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::416526184275:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-Ud27U2DO7Xwy
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::416526184275:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-10-26T09:56:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1399"
  uid: cd80f77f-27ee-459e-ae01-4301d2f7edc0
